language: java
jdk:
  - oraclejdk8
sudo: false
install: true
addons:
  sonarcloud:
    organization: "svartifoss-github" # the key of the org you chose at step #3
    token:
      secure: 76df04dfd92e4759dc127a08db0ebeba653c26a9 # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install jacoco:report coveralls:report sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
  #mvn sonar:sonar \
  #-Dsonar.projectKey=svartifoss_jaxb2-pluralize \
  #-Dsonar.organization=svartifoss-github \
  #-Dsonar.host.url=https://sonarcloud.io \
  #-Dsonar.login=76df04dfd92e4759dc127a08db0ebeba653c26a9

after_success:
  - bash <(curl -s https://codecov.io/bash)
